# Site settings
title:              Mahdieh's Robotic Project Portfolio
email:              m.nejati@u.northwestern.edu
description:        "Portfolio for documenting robotics projects in the  MSR program at Northwestern University"
url:                "http://localhost:4000"
baseurl:            /website

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/


